#!/bin/bash

# Looks at the running processes in an attempt to determine which step
# devtest is currently executing

current=$(ps auxww | grep devtest_ | grep -v grep)
if [ -n "$current" ]; then
    echo "Devtest current step:"
    echo $(echo $current | sed 's/.*devtest_\([a-z]\+\).sh.*/\1/')
    image=$(ps auxww | grep disk-image-create | grep -v grep)
    if [ -n "$image" ]; then
        image=$(echo $image | sed 's|.*-o \([a-z\/-]\+\).*|\1|')
        echo " - building image: $(basename $image)"
    fi
    waitfor=$(ps auxww | grep wait_for | grep -v grep)
    if [ -n "$waitfor" ]; then
        echo " - waiting for deployment"
    fi
else
    echo "No running devtest found."
fi
