heat_template_version: 2015-04-30

parameters:

  server:
    type: string

resources:

  RabbitmqFdLimitConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        set -eux
        set -o pipefail
        cat << EOF >> /etc/security/limits.conf
        rabbitmq   hard   nofile   16384
        rabbitmq   soft   nofile   16384
        EOF


  RabbitmqFdLimitDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config: {get_resource: RabbitmqFdLimitConfig}
      server: {get_param: server}

outputs:
  deploy_stdout:
    description: Deployment stdout
    value: {get_attr: [RabbitmqFdLimitDeployment, deploy_stdout]}

