
resource_registry:
  OS::TripleO::BlockStorage::Net::SoftwareConfig: nic-configs/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml
  OS::TripleO::ObjectStorage::Net::SoftwareConfig: nic-configs/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: nic-configs/ceph-storage.yaml

parameter_defaults:
  ControlPlaneSubnetCidr: '24'
  ControlPlaneDefaultRoute: 192.0.2.1
  EC2MetadataIp: 192.0.2.1
  ExternalNetCidr: 10.0.0.0/24
  ExternalAllocationPools: [{"start": "10.0.0.10", "end": "10.0.0.50"}]
  ExternalInterfaceDefaultRoute: 10.0.0.1
  ExternalNetworkVlanID: 1
  NeutronExternalNetworkBridge: "''"
  InternalApiNetCidr: 172.17.0.0/24
  InternalApiAllocationPools: [{"start": "172.17.0.10", "end": "172.17.0.250"}]
  InternalApiNetworkVlanID: 2
  StorageNetCidr: 172.18.0.0/24
  StorageAllocationPools: [{"start": "172.18.0.10", "end": "172.18.0.250"}]
  StorageNetworkVlanID: 3
  StorageMgmtNetCidr: 172.19.0.0/24
  StorageMgmtAllocationPools: [{"start": "172.19.0.10", "end": "172.19.0.250"}]
  StorageMgmtNetworkVlanID: 4
  TenantNetCidr: 172.16.0.0/24
  TenantAllocationPools: [{"start": "172.16.0.10", "end": "172.16.0.250"}]
  TenantNetworkVlanID: 5
  ManagementNetCidr: 172.20.0.0/24
  ManagementAllocationPools: [{"start": "172.20.0.10", "end": "172.20.0.250"}]
  ManagementNetworkVlanID: 6
  DnsServers: ["8.8.8.8", "8.8.4.4"]
