heat_template_version: 2014-10-16

description: Template for deploying OpenStack BMC nodes.  Can be wrapped in a ResourceGroup for scaling.

# Usage: heat stack-create -f ./openstack-bmc.yaml -e ./env.json ./resource-registry.yaml -P node_count=3 baremetal
# Ensure force_config_drive is _not_ set in nova.conf

parameters:
  bmc_flavor:
    type: string
    default: m1.small

  bmc_image:
    type: string
    default: openstack-bmc

  baremetal_image:
    type: string
    default: empty

  key_name:
    type: string
    default: default

  node_count:
    type: number
    default: 1

  private_net:
    type: string
    default: private

  provision_net:
    type: string
    default: provision

  bmc_prefix:
    type: string
    default: bmc

  baremetal_prefix:
    type: string
    default: baremetal

  os_user:
    type: string
    default: admin

  os_password:
    type: string
    default: password
    hidden: true

  os_tenant:
    type: string
    default: admin

  os_auth_url:
    type: string

resources:
  openstack_bmc_servers:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: node_count}
      resource_def:
        type: OS::QuintupleO::BMC
        properties:
            bmc_flavor: {get_param: bmc_flavor}
            bmc_image: {get_param: bmc_image}
            baremetal_image: {get_param: baremetal_image}
            key_name: {get_param: key_name}
            private_net: {get_param: private_net}
            provision_net: {get_param: provision_net}
            suffix: _%index%
            bmc_prefix: {get_param: bmc_prefix}
            baremetal_prefix: {get_param: baremetal_prefix}
            os_user: {get_param: os_user}
            os_password: {get_param: os_password}
            os_tenant: {get_param: os_tenant}
            os_auth_url: {get_param: os_auth_url}
