heat_template_version: 2014-10-16

parameters:
  bmc_flavor:
    type: string

  bmc_image:
    type: string

  baremetal_image:
    type: string

  key_name:
    type: string

  bmc_prefix:
    type: string

  baremetal_prefix:
    type: string

  private_net:
    type: string

  provision_net:
    type: string

  suffix:
    type: string

  os_user:
    type: string

  os_password:
    type: string
    hidden: true

  os_tenant:
    type: string

  os_auth_url:
    type: string

resources:
    OpenStackBMCServer:
        type: OS::Nova::Server
        properties:
            flavor: {get_param: bmc_flavor}
            image: {get_param: bmc_image}
            key_name: {get_param: key_name}
            networks:
                - network: {get_param: private_net}
            user_data_format: SOFTWARE_CONFIG
            name:
                list_join:
                    - ''
                    - - {get_param: bmc_prefix}
                      - {get_param: suffix}

    BaremetalFlavor:
        type: OS::Nova::Flavor
        properties:
            disk: 50
            extra_specs: {"libvirt:pxe-first": 1}
            ram: 4096
            vcpus: 2

    OpenStackBaremetalServer:
        type: OS::Nova::Server
        properties:
            flavor: {get_resource: BaremetalFlavor}
            image: {get_param: baremetal_image}
            config_drive: false
            key_name: {get_param: key_name}
            networks:
                - network: {get_param: provision_net}
            name:
                list_join:
                    - ''
                    - - {get_param: baremetal_prefix}
                      - {get_param: suffix}

    ServerConfig:
        type: OS::Heat::StructuredConfig
        properties:
            group: os-apply-config
            config:
                bmc:
                    instance: {get_input: instance}
                    user: {get_param: os_user}
                    password: {get_param: os_password}
                    tenant: {get_param: os_tenant}
                    auth_url: {get_param: os_auth_url}

    ServerDeployment:
        type: OS::Heat::StructuredDeployment
        properties:
            config: {get_resource: ServerConfig}
            server: {get_resource: OpenStackBMCServer}
            signal_transport: NO_SIGNAL
            input_values:
                instance:
                    list_join:
                    - ''
                    - - {get_param: baremetal_prefix}
                      - {get_param: suffix}
